---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте с помощью почты или с использованием учётной записи GitHub или Discord
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью почты или с использованием учётной записи GitHub или Discord
  - Пользователь должен иметь возможность просматривать свою статистику и историю завершённых игр
  - Пользователь должен иметь возможность создавать игру, выбирая нужные ему параметры (сложность, с кем игра, время, тип задачи)
  - Пользователь должен иметь возможность выбирать оппонента для игры из предложенного сервисом списка
  - Пользователь должен иметь возможность наблюдать за турнирами
  - Пользователь должен иметь возможность создавать турниры, к которым может присоединиться в качестве игрока или наблюдателя любой желающий
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Пользователь должен иметь возможность выставлять в настройках нужный ему язык программирования по умолчанию
  - Пользователь должен иметь возможность привязать свои учётные записи GitHub или/и Discord
  - Пользователь должен иметь возможность отвязать привязанные учётные записи GitHub или/и Discord
  - Пользователь должен иметь возможность просматривать рейтинг пользователей